project:
  type: website
  output-dir: docs

website:
  title: "Python Blog"
  navbar:
    right:
      - text: Ana Sayfa
        href: index.qmd
      - text: Yazılar
        href: posts.qmd
      - text: Paketler
        menu:
          - text: isyatirimhisse
            href: https://github.com/urazakgul/isyatirimhisse
            target: _blank
          - text: EIAOpenData
            href: https://github.com/urazakgul/EIAOpenData
            target: _blank

format:
  html:
    page-layout: full
    lang: tr
    date-format: "MMMM D, YYYY"
    theme:
      light: litera
      dark: solar
    css: styles.css

execute:
  freeze: auto